'use client';

import { useState, useEffect } from 'react';
import { Receipt, Save, ChevronDown, ChevronUp, ExternalLink } from 'lucide-react';

export default function CloverPOSClient() {
    const [settings, setSettings] = useState({ app_id: '', app_secret: '' });
    const [saving, setSaving] = useState(false);
    const [msg, setMsg] = useState('');
    const [showGuide, setShowGuide] = useState(false);

    useEffect(() => {
        fetch('/api/super-admin/pos/settings').then(r => r.json()).then(d => {
            const cs = d.settings?.pos_clover_settings || {};
            setSettings({ app_id: cs.app_id || '', app_secret: cs.app_secret ? '••••••••' : '' });
        });
    }, []);

    async function save() {
        setSaving(true);
        const payload: Record<string, string> = { app_id: settings.app_id };
        if (settings.app_secret && !settings.app_secret.startsWith('••')) {
            payload.app_secret = settings.app_secret;
        }
        await fetch('/api/super-admin/pos/settings', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ clover_settings: payload }),
        });
        setSaving(false);
        setMsg('Clover POS settings saved.');
        setTimeout(() => setMsg(''), 3000);
    }

    return (
        <div className="p-8 max-w-3xl">
            <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 bg-green-600/20 rounded-xl flex items-center justify-center">
                    <Receipt className="w-5 h-5 text-green-400" />
                </div>
                <div>
                    <h1 className="text-2xl font-bold text-white">Clover POS Configuration</h1>
                    <p className="text-slate-400 text-sm">Global developer app credentials for Clover integration</p>
                </div>
            </div>

            {msg && <div className="mb-6 px-4 py-3 bg-green-900/30 border border-green-700/50 text-green-300 rounded-lg text-sm">{msg}</div>}

            {/* Setup Guide */}
            <div className="mb-6 bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
                <button
                    onClick={() => setShowGuide(!showGuide)}
                    className="w-full flex items-center justify-between px-6 py-4 text-left"
                >
                    <span className="text-white font-medium">Setup Guide — Clover API Access</span>
                    {showGuide ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
                </button>
                {showGuide && (
                    <div className="px-6 pb-6 space-y-4 border-t border-slate-800">
                        <ol className="space-y-4 mt-4">
                            <li className="flex gap-3">
                                <span className="flex-shrink-0 w-6 h-6 bg-green-600/20 text-green-400 rounded-full flex items-center justify-center text-xs font-bold">1</span>
                                <div>
                                    <p className="text-white font-medium text-sm">Create a Clover Developer Account</p>
                                    <p className="text-slate-400 text-xs mt-1">Go to <span className="text-green-400">www.clover.com/developers</span> and register an app. Select &ldquo;Read Orders&rdquo; and &ldquo;Read Inventory&rdquo; scopes.</p>
                                </div>
                            </li>
                            <li className="flex gap-3">
                                <span className="flex-shrink-0 w-6 h-6 bg-green-600/20 text-green-400 rounded-full flex items-center justify-center text-xs font-bold">2</span>
                                <div>
                                    <p className="text-white font-medium text-sm">Get App ID and Secret</p>
                                    <p className="text-slate-400 text-xs mt-1">In your Clover Developer dashboard, note your <strong className="text-white">App ID</strong> and <strong className="text-white">App Secret</strong> from the app detail page.</p>
                                </div>
                            </li>
                            <li className="flex gap-3">
                                <span className="flex-shrink-0 w-6 h-6 bg-green-600/20 text-green-400 rounded-full flex items-center justify-center text-xs font-bold">3</span>
                                <div>
                                    <p className="text-white font-medium text-sm">Organization-level setup</p>
                                    <p className="text-slate-400 text-xs mt-1">Each organization must install the app on their Clover device and then enter their <strong className="text-white">Merchant ID</strong> and the <strong className="text-white">API Access Token</strong> generated by the OAuth flow. They enter these in Admin → Settings → Sync POS.</p>
                                </div>
                            </li>
                            <li className="flex gap-3">
                                <span className="flex-shrink-0 w-6 h-6 bg-green-600/20 text-green-400 rounded-full flex items-center justify-center text-xs font-bold">4</span>
                                <div>
                                    <p className="text-white font-medium text-sm">API Endpoints used</p>
                                    <p className="text-slate-400 text-xs mt-1 font-mono">GET /v3/merchants/&#123;mid&#125;/orders?filter=clientCreatedTime&gt;TS&amp;expand=lineItems</p>
                                    <p className="text-slate-500 text-xs mt-1">Base URL: api.clover.com</p>
                                </div>
                            </li>
                        </ol>
                    </div>
                )}
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
                <h2 className="text-white font-semibold mb-5">Global Developer Credentials</h2>
                <div className="space-y-4">
                    <div>
                        <label className="block text-slate-400 text-xs font-medium mb-1.5 uppercase tracking-wider">App ID</label>
                        <input
                            type="text"
                            value={settings.app_id}
                            onChange={e => setSettings(s => ({ ...s, app_id: e.target.value }))}
                            className="w-full bg-slate-800 border border-slate-700 text-white rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-green-500"
                            placeholder="Clover App ID"
                        />
                    </div>
                    <div>
                        <label className="block text-slate-400 text-xs font-medium mb-1.5 uppercase tracking-wider">App Secret</label>
                        <input
                            type="password"
                            value={settings.app_secret}
                            onChange={e => setSettings(s => ({ ...s, app_secret: e.target.value }))}
                            className="w-full bg-slate-800 border border-slate-700 text-white rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-green-500"
                            placeholder="Enter to update secret"
                        />
                        <p className="text-slate-500 text-xs mt-1">Leave masked to keep existing value</p>
                    </div>
                </div>
                <button
                    onClick={save}
                    disabled={saving}
                    className="mt-5 flex items-center gap-2 px-4 py-2.5 bg-green-600 hover:bg-green-500 disabled:opacity-50 text-white rounded-lg text-sm font-medium transition-colors"
                >
                    <Save className="w-4 h-4" />
                    {saving ? 'Saving…' : 'Save Clover Settings'}
                </button>
            </div>

            <div className="mt-4 text-center">
                <a href="https://www.clover.com/developers" target="_blank" rel="noreferrer"
                    className="text-slate-400 hover:text-white text-xs inline-flex items-center gap-1">
                    Clover Developer Portal <ExternalLink className="w-3 h-3" />
                </a>
            </div>
        </div>
    );
}
