#!/bin/bash
# setup-backup-cron.sh — Install automatic database backup cron jobs.
# Run once on the server after initial setup.
# Usage: sudo bash scripts/setup-backup-cron.sh

set -e

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BACKUP_DIR="/opt/topshelf/backups"
LOG_DIR="/opt/topshelf/logs"
CRON_USER="${SUDO_USER:-$(whoami)}"

echo "=========================================="
echo "  TopShelf Automatic Backup Setup"
echo "=========================================="
echo "  App directory : $APP_DIR"
echo "  Backup dir    : $BACKUP_DIR"
echo "  Running as    : $CRON_USER"
echo ""

# Ensure directories exist
mkdir -p "$BACKUP_DIR" "$LOG_DIR"
chmod 755 "$BACKUP_DIR" "$LOG_DIR"
chown "$CRON_USER:$CRON_USER" "$BACKUP_DIR" "$LOG_DIR" 2>/dev/null || true

CRON_TMP=$(mktemp)

# Export current crontab for the user (may be empty)
crontab -u "$CRON_USER" -l 2>/dev/null > "$CRON_TMP" || true

# Remove any old topshelf backup entries so we don't double-install
grep -v "topshelf.*backup\|backup-db.sh" "$CRON_TMP" > "${CRON_TMP}.clean" && mv "${CRON_TMP}.clean" "$CRON_TMP"

# Add new entries:
#   Every 6 hours          — regular backup
#   Daily at 2am           — daily backup (tagged separately)
#   Weekly Sunday 3am      — weekly backup
cat >> "$CRON_TMP" <<CRON
# TopShelf database backups (installed by setup-backup-cron.sh)
0 */6 * * *  cd "$APP_DIR" && bash scripts/backup-db.sh "$BACKUP_DIR" "cron-6h"  >> "$LOG_DIR/backup.log" 2>&1
0 2   * * *  cd "$APP_DIR" && bash scripts/backup-db.sh "$BACKUP_DIR" "cron-daily" >> "$LOG_DIR/backup.log" 2>&1
0 3   * * 0  cd "$APP_DIR" && bash scripts/backup-db.sh "$BACKUP_DIR" "cron-weekly" >> "$LOG_DIR/backup.log" 2>&1
CRON

crontab -u "$CRON_USER" "$CRON_TMP"
rm -f "$CRON_TMP"

echo "Cron jobs installed for user: $CRON_USER"
echo ""
echo "Schedule:"
echo "  Every 6 hours   — automatic backup"
echo "  Daily at 2am    — daily backup"
echo "  Weekly Sun 3am  — weekly backup"
echo ""
echo "Logs: $LOG_DIR/backup.log"
echo ""

# ── S3 Configuration ─────────────────────────────────────────────────────────
echo "=========================================="
echo "  S3 Offsite Backup Configuration"
echo "=========================================="
echo ""
echo "To enable S3 offsite backups (strongly recommended):"
echo ""
printf "  Configure S3 now? (yes/no): "
read -r CONFIGURE_S3

if [ "$CONFIGURE_S3" = "yes" ]; then
    printf "  AWS S3 Bucket name: "
    read -r S3_BUCKET
    printf "  AWS Region (e.g. us-east-1): "
    read -r S3_REGION
    printf "  AWS Access Key ID: "
    read -r S3_KEY_ID
    printf "  AWS Secret Access Key: "
    read -rs S3_SECRET
    echo ""

    S3_ENV_FILE="/opt/topshelf/s3-backup.env"
    cat > "$S3_ENV_FILE" <<ENV
# TopShelf S3 backup configuration
# Generated by setup-backup-cron.sh on $(date)
TOPSHELF_S3_BUCKET="$S3_BUCKET"
TOPSHELF_S3_REGION="$S3_REGION"
ENV
    chmod 600 "$S3_ENV_FILE"
    chown "$CRON_USER:$CRON_USER" "$S3_ENV_FILE" 2>/dev/null || true

    # Configure AWS CLI credentials
    AWS_CRED_DIR="/home/$CRON_USER/.aws"
    mkdir -p "$AWS_CRED_DIR"
    chmod 700 "$AWS_CRED_DIR"

    cat > "$AWS_CRED_DIR/credentials" <<CRED
[default]
aws_access_key_id = $S3_KEY_ID
aws_secret_access_key = $S3_SECRET
CRED
    chmod 600 "$AWS_CRED_DIR/credentials"
    chown -R "$CRON_USER:$CRON_USER" "$AWS_CRED_DIR" 2>/dev/null || true

    cat > "$AWS_CRED_DIR/config" <<CFG
[default]
region = $S3_REGION
output = json
CFG
    chmod 600 "$AWS_CRED_DIR/config"

    echo "S3 configuration saved to $S3_ENV_FILE"
    echo "AWS credentials saved to $AWS_CRED_DIR/credentials"
    echo ""

    # Test the S3 connection
    echo "Testing S3 connection..."
    if command -v aws >/dev/null 2>&1; then
        if aws s3 ls "s3://$S3_BUCKET" --region "$S3_REGION" >/dev/null 2>&1; then
            echo "S3 connection: OK — bucket is accessible."
        else
            echo "WARNING: Could not access s3://$S3_BUCKET — check bucket name, region, and IAM permissions."
            echo "         Required IAM permissions: s3:PutObject, s3:GetObject, s3:ListBucket"
        fi
    else
        echo "NOTE: aws CLI not installed. Install it for S3 uploads to work:"
        echo "  curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip"
        echo "  unzip /tmp/awscliv2.zip -d /tmp && sudo /tmp/aws/install"
    fi
else
    echo "Skipping S3 setup. You can configure it later in Super Admin > Integrations."
    echo "Or re-run this script: sudo bash scripts/setup-backup-cron.sh"
fi

echo ""
echo "=========================================="
echo "  Setup complete!"
echo "  Run a test backup now:"
echo "    cd $APP_DIR && bash scripts/backup-db.sh"
echo "=========================================="
